<?php
echo $this->doctype();
?><html lang="en">
<head>
<meta charset="utf-8"><?php
echo $this->headTitle();
echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
					  ?><base href="<?php echo $this->serverUrl($this->baseHref()); ?>" />
<!-- Le styles -->
<?php
					  echo $this->headLink(array(
								  'rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->serverUrl($this->baseHref() . '/Theme/Image/favicon.ico')
							  ))->prependStylesheet($this->serverUrl($this->baseHref() . '/Theme/CSS'));
?>
<!-- Scripts -->
<?php
echo $this->headScript()->prependFile($this->serverUrl($this->baseHref() . '/Theme/Javascript/html5.js'), 'text/javascript', array(
			'conditional' => 'lt IE 9'
		))->prependFile($this->serverUrl($this->baseHref() . '/Theme/Javascript'));
?>
</head>
    <body>
<?php $partial = array(
	'navigator/layout', 'default'
);
$container = $this->navigation('Navigator')->getContainer();
echo $this->navigation(clone $container)->menu()->setPartial($partial)->render();
?>

<?php $partial = array(
	'breadcrumb/layout', 'default'
);
echo $this->navigation(clone $container)->breadcrumbs()->setPartial($partial)->render();
?>
<?php echo $this->content; ?></body>
</html>