<?php
$container = $this->navigation('Navigator')->getContainer();
$menucontainer = clone $container;
$breadcrumbcontainer = clone $container;
echo $this->doctype();
?><html lang="en">
<head>
<?php
echo $this->headTitle();
?><meta charset="utf-8">
<?php
echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
?><base href="<?php echo $this->serverUrl($this->baseHref()); ?>" />
<!-- Le styles -->
<?php
echo $this->headLink(array(
				'rel' => 'shortcut icon',
				'type' => 'image/vnd.microsoft.icon',
				'href' => $this->serverUrl($this->baseHref() . '/Theme/Image/favicon.ico')
		))->prependStylesheet($this->serverUrl($this->baseHref() . '/Theme/CSS'), 'all');
?><!-- Scripts -->
<?php
echo $this->headScript()->prependFile($this->serverUrl($this->baseHref() . '/Theme/Javascript/html5.js'), 'text/javascript', array(
				'conditional' => 'lt IE 9'
		))->prependFile($this->serverUrl($this->baseHref() . '/Theme/Javascript'));
?></head>
    <body><div class="container">
	    <div class="layoutHeader">
	   		<div class="layoutHeaderBG">
	   			<div class="layoutNavigator">
	   			<?php
$partial = array(
		'navigator/layout',
		'default'
);
echo $this->navigation($menucontainer)->menu()->setPartial($partial)->render();
				   ?></div>
			</div>
	    </div>
	    <?php
				   if (!empty($this->left)) {
		?><div class="layoutLeft">
		<?php echo $this->left; ?></div>
		<?php
		}
		if (!empty($this->right)) {
		?><div class="layoutRight">
		<?php echo $this->right; ?></div>
		<?php
		}
		?><div class="layoutCenter" style="margin: 5px <?php echo (!empty($this->right) ? '235px' : '0'); ?> 0 <?php echo (!empty($this->left) ? '235px' : '0'); ?>;">
		<?php
		$partial = array(
				'breadcrumb/layout',
				'default'
		);
		echo $this->navigation($breadcrumbcontainer)->breadcrumbs()->setPartial($partial)->render();
		if (!empty($this->after)) {
		?><div class="layoutBefore">
		<?php echo $this->before; ?></div>
		<?php
		}
		?><div class="layoutContent">
		<div class="body">			
		<?php echo $this->content; ?></div>
		</div>
		<?php
		if (!empty($this->after)) {
		?><div class="layoutAfter">
		<?php echo $this->after; ?></div>
		<?php
		}
		?></div>
	    <div class="layoutFooter">
	    <?php echo sprintf($this->translate('text_copyright'), date("Y", time()), $this->htmlLink($this->baseHref(), $this->translate('text_system_name'), array(
						'class' => 'copyright'
				)));
		?></div>
    </div></body>
</html>